version: '3'
services:
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nginx-relayer-node
        volumes:
            - ./build/conf:/app/build/conf
            - ./build/dhparam:/app/build/dhparam
            - ./build/certificates:/app/build/certificate
            - ./build/challenge:/app/build/challenge
            - /var/www/html:/var/www/html
        container_name: nginx-relayer-node
        restart: unless-stopped
        networks:
            - app-network
    webserver:
        image: nginx
        container_name: nginx-relayer
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./build/conf:/etc/nginx/conf.d
            - ./build/dhparam:/etc/ssl/certs
            - ./build/certificates:/etc/letsencrypt/live
            - ./build/challenge:/challenge
            - /var/www/html:/var/www/html
            - ./scripts:/scripts
        command:
            - "./scripts/run_nginx.sh"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
          