version: '3'
services:
    webserver:
        image: nginx
        container_name: ${PROJECT}-webserver
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./build/conf:/etc/nginx/conf.d
            - ./build/dhparam.pem:/etc/ssl/certs
            - /var/www/html:/var/www/html
            - /etc/letsencrypt:/etc/letsencrypt
            - /var/lib/letsencrypt:/var/lib/letsencrypt
            - ./:/src
        command:
            - "./src/scripts/run_nginx.sh"
        extra_hosts:
            - "host.docker.internal:host-gateway"
    
networks:
    app-network:
        driver: bridge
          
          